"""Type stubs for the compiled pybox3d._pybox3d extension.

Mypy has no visibility into the C extension source, so this file is its
only view of the extension's public API -- keep it in sync by hand as the
C-API surface (src/pybox3d/_ext/*.c) changes.
"""

from __future__ import annotations

from collections.abc import Sequence
from typing import NamedTuple, Union

__version__: str

BOX_KIND_AABB: int
BOX_KIND_OBB: int

VecLike = Union["Vec3", Sequence[float]]
QuatLike = Union["Quat", Sequence[float]]

class Box3DError(RuntimeError): ...
class CapacityError(Box3DError): ...

class Vec3:
    x: float
    y: float
    z: float

    def __init__(self, x: float = 0.0, y: float = 0.0, z: float = 0.0) -> None: ...
    def __add__(self, other: Vec3) -> Vec3: ...
    def __sub__(self, other: Vec3) -> Vec3: ...
    def __mul__(self, scalar: float) -> Vec3: ...
    def __rmul__(self, scalar: float) -> Vec3: ...
    def __neg__(self) -> Vec3: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def dot(self, other: VecLike) -> float: ...
    def cross(self, other: VecLike) -> Vec3: ...
    def length(self) -> float: ...
    def length_squared(self) -> float: ...
    def normalized(self) -> Vec3: ...
    def to_tuple(self) -> tuple[float, float, float]: ...

class Quat:
    x: float
    y: float
    z: float
    w: float

    def __init__(self, x: float = 0.0, y: float = 0.0, z: float = 0.0, w: float = 1.0) -> None: ...
    def __mul__(self, other: Quat) -> Quat: ...
    def __eq__(self, other: object) -> bool: ...
    @classmethod
    def from_axis_angle(cls, axis: VecLike, angle_radians: float) -> Quat: ...
    def normalized(self) -> Quat: ...
    def conjugate(self) -> Quat: ...
    def rotate_vec3(self, v: VecLike) -> Vec3: ...
    def to_mat3(self) -> tuple[float, ...]: ...

class ContactInfo(NamedTuple):
    normal: Vec3
    penetration: float

class RayHit(NamedTuple):
    t: float
    point: Vec3
    normal: Vec3

class Box3D:
    center: Vec3
    half_extents: Vec3
    orientation: Quat
    kind: int

    def __init__(
        self, center: VecLike, half_extents: VecLike, orientation: QuatLike | None = None
    ) -> None: ...
    def contains_point(self, point: VecLike) -> bool: ...
    def aabb(self) -> tuple[Vec3, Vec3]: ...
    def overlaps(self, other: Box3D) -> ContactInfo | None: ...
    def raycast(self, origin: VecLike, direction: VecLike, max_t: float = ...) -> RayHit | None: ...

class RigidBody:
    position: Vec3
    orientation: Quat
    linear_velocity: Vec3
    angular_velocity: Vec3
    mass: float
    restitution: float
    friction: float
    is_static: bool
    @property
    def inv_mass(self) -> float: ...
    @property
    def shape(self) -> Box3D: ...
    def __init__(self, position: VecLike, half_extents: VecLike, mass: float = 0.0) -> None: ...
    def apply_force(self, force: VecLike, point: VecLike | None = None) -> None: ...
    def apply_impulse(self, impulse: VecLike, point: VecLike | None = None) -> None: ...
    def clear_accumulators(self) -> None: ...

class DistanceJoint:
    rest_length: float
    @property
    def body_a(self) -> RigidBody: ...
    @property
    def body_b(self) -> RigidBody: ...

class World:
    gravity: Vec3
    default_restitution: float
    default_friction: float
    @property
    def body_count(self) -> int: ...
    @property
    def joint_count(self) -> int: ...
    def __init__(self, gravity: VecLike = ..., initial_capacity: int = 8) -> None: ...
    def add_body(self, body: RigidBody) -> RigidBody: ...
    def get_body(self, index: int) -> RigidBody: ...
    def remove_body(self, index: int) -> None: ...
    def add_joint(
        self, body_a: RigidBody, body_b: RigidBody, rest_length: float | None = None
    ) -> DistanceJoint: ...
    def get_joint(self, index: int) -> DistanceJoint: ...
    def remove_joint(self, index: int) -> None: ...
    def step(self, dt: float) -> None: ...
